config/routes.rb
Rails.application.routes.draw do

  root 'boards#index'

  devise_for :users


  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :tasks
    get 'taskup/:id', to: 'tasks#up', as: 'task_up'
    get 'taskdown/:id', to: 'tasks#down', as: 'task_down'
  end

  get 'listup/:id', to: 'lists#up', as: 'list_up'
  get 'listdown/:id', to: 'lists#down', as: 'list_down'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true
  has_many :lists, dependent: :destroy

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy

  validates_presence_of :title, :priority

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates_presence_of :title, :priority
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :gender, :age
  validates_inclusion_of :gender, in: %w(Male Female Other)
  validates :age, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 120 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age, :gender])
     end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:edit, :show, :update, :destroy]

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @lists = @board.lists.order(priority: :DESC)
  end

  def destroy
    @board.destroy
    redirect_to root_path
  end


  private
    def board_params
      params.require(:board).permit(:title)
    end

    def set_board
      @board = Board.find(params[:id])
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board, except: [:up, :down]
  before_action :set_list, only: [:show, :edit, :update, :destroy, :up, :down]

  def index
  end

  def new
    @list = List.new
  end

  def create
    @list = @board.lists.create(list_params)
    if @list.save
      redirect_to board_path(@board)

    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to board_path(@board)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @list.destroy
    redirect_to board_path(@board)
  end

  def up
    list1 = List.where('priority > ?', @list.priority).order(:priority).first
    @list.priority = list1.priority + 1
    @list.save
    redirect_to board_path(@list.board_id)
  end

  def down
    list1 = List.where('priority < ?', @list.priority).order(:priority).last
    @list.priority = list1.priority - 1
    @list.save
    redirect_to board_path(@list.board_id)
  end

  private
    def list_params
      params.require(:list).permit(:title, :priority)
    end

    def set_board
      @board = Board.find(params[:board_id])
    end


    def set_list
      @list = List.find(params[:id])
    end



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only: [:edit, :update, :destroy, :up, :down]


  def new
    @task = Task.new
    render :form
  end

  def create
    @task = @list.tasks.new(task_params)
    if @task.save

      redirect_to board_path(@list.board_id)
    else
      render :form
    end
  end

  def edit
    render :form
  end

  def update
    if @task.update(task_params)
      redirect_to board_path(@list.board_id)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to board_path(@list.board_id)
  end

  def up
    task1 = Task.where('priority > ?', @task.priority).order(:priority).first
    @task.priority = task1.priority + 1
    @task.save
    redirect_to board_path(@list.board_id)
  end

  def down
    task1 = Task.where('priority < ?', @task.priority).order(:priority).last
    @task.priority = task1.priority - 1
    @task.save
    redirect_to board_path(@list.board_id)
  end



  private
    def task_params
      params.require(:task).permit(:title, :priority, :body)
    end

    def set_list
      @list = List.find(params[:list_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_for @board do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/boards/edit.html.erb
<h1>Boards Edit</h1>
<%= render 'boards/form' %>

app/views/boards/index.html.erb
<h1>Boards Index</h1>

<%= link_to 'Add Board', new_board_path %>
<br />
<% @boards.each do |board| %>
  <%= board.title %>
  <%= link_to 'View', board_path(board) %>
  <%= link_to 'Edit', edit_board_path(board) %>
  <%= link_to 'Delete', board_path(board), {method: :delete} %>
  <br />
<% end %>

app/views/boards/new.html.erb
<h1>Boards New</h1>
<%= render 'boards/form' %>

app/views/boards/show.html.erb
<h4>Boards Show</h4>
<h1><%= @board.title %></h1>
<%= link_to 'Add List', new_board_list_path(@board) %>
<br />
<hr />
<% @lists.each do |list| %>
  <h1><%= list.title%></h1>
  <br />
    <% list.tasks.order(priority: :DESC).each do |task| %>
      <%= task.title %>
      <br />
      <%= task.body %>
      <br />
      <%= link_to 'Edit', edit_list_task_path(list, task) %>
      <%= link_to 'Delete', list_task_path(list, task), {method: :delete} %>
      <%= link_to 'up', list_task_up_path(list, task) %>
      <%= link_to 'down', list_task_down_path(list, task) %>
      <hr />
    <% end %>
  <%= link_to 'Add Task', new_list_task_path(list) %>
  <%= link_to 'View', board_list_path(@board, list) %>
  <%= link_to 'Edit', edit_board_list_path(@board, list) %>
  <%= link_to 'Delete', board_list_path(@board, list), {method: :delete} %>
  <%= link_to 'up', list_up_path(list) %>
  <%= link_to 'down', list_down_path(list) %>
  <hr />
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div>
      <%= link_to 'Home', root_path %>
      <%= button_to 'Log Out', destroy_user_session_path, method: :delete %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for [@board, @list] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :priority %>
  <%= f.text_field :priority %>
  <%= f.submit %>

<% end %>

app/views/lists/edit.html.erb
<h1>Lists Edit</h1>
<%= render 'form'%>

app/views/lists/index.html.erb
<h1>Lists Index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Lists New</h1>
<%= render 'form' %>

app/views/lists/show.html.erb
<h4>Lists Show Page</h4>
<br />
<h1><%= @list.title %></h1>
<% @list.tasks.each do |task| %>
  <%= task.title %>
<% end %>

app/views/tasks/form.html.erb
<%= form_for [@list, @task] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :priority %>
  <%= f.text_field :priority %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>